development:
  adapter: postgresql
  encoding: unicode
  database: wanna
  pool: 5
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  database: wanna
  pool: 25
  host: 127.0.0.1
